blank_issues_enabled: false

contact_links:
  - name: General question
    url: https://github.com/roryobrien33/SS-AI-EFFECT-Data-Catalog-IssueForms/discussions
    about: Ask general questions here.
